### ISSUE TITLE
nearsk unable to find certain packages

### ISSUE THREAD

**Issue by wiredhikari** [nix-community/naersk#244]
On using naersk to build the package, it sometimes is able to locate the package and often gives the error as package not found.
[Link](https://github.com/fedimint/minimint/runs/6732262575?check_suite_focus=true#step:4:3816) to logs. [Link](https://github.com/fedimint/minimint/issues/90) to the issue.

**Comment by Patryk27** [comment]
Hi,

Thanks for reporting - that's going to be fixed by https://github.com/nix-community/naersk/pull/234 🙂

For the time being, you can:
```
$ niv update naersk -r 23088edbc9e326cad7522b69e9c20aa463a496f2
```
... (which just pins `naersk` to commit from that pull request) and voilà, `nix-build` works again.

To avoid cluttering the issue list, I'm gonna go ahead and close this one - if you want to get notified when this gets merged, feel free to subscribe to changes from that PR.

Thanks & cheers!
