### ISSUE TITLE
build failure when compiling libffi-sys

### ISSUE THREAD

**Issue by cmoog** [nix-community/naersk#267]
I'm seeing the following build failure building a crate with libffi-sys as a dependency.

```
       >   process didn't exit successfully: `/build/dummy-src/target/release/build/libffi-sys-0d06b1d09a6a10b6/build-script-build` (exit status: 101)
       >   --- stderr
       >   configure: line 2319: config.log: Permission denied
       >   configure: line 2329: config.log: Permission denied
       >   thread 'main' panicked at 'Configuring libffi', /sources/libffi-sys-2.0.0/build/common.rs:8:5
```

Has anyone found a workaround via some preBuild patching?

**Comment by Patryk27** [comment]
Hi,

As far as I see, that's a bug in libffi-sys - its build script [incorrectly](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) assumes that it can modify its source directory (in this case, by executing `./configure` in it), which just happens to work in a regular environment, but breaks in Naresk - I'd suggest contacting the crate authors to get this fixed.

That being said, there _is_ a way to hack-around this issue in Naresk - try something like:
```
naersk.buildPackage {
  # ...

  # singleStep = true; # Might be required, might be not

  preConfigure = ''
    mkdir /tmp/deps
    rsync -aL $crate_sources/ /tmp/deps
    chmod 777 -R /tmp/deps
    ls -al /tmp/deps
    crate_sources=/tmp/deps
  '';

  preBuild = ''
    echo '[source]' > $CARGO_HOME/config
    echo '"crates-io" = { "replace-with" = "nix-sources" }' >> $CARGO_HOME/config
    echo '"nix-sources" = { directory = "/tmp/deps" }' >> $CARGO_HOME/config
  '';
}
```
This hack works by copy-pasting source codes of all of the dependencies into readable-and-writable temporary directory under `/tmp/deps` (as compared to referencing those sources through _read-only_ `/nix/store`), which is a bit suboptimal (each building will always copy-paste the entire dependency tree, which might use lots of memory and/or I/O), but well - should work.

As I've said, since that's a bug in an external library, I'm going to close the issue in here - thanks for reporting, though, and let's hope the upstream fixes their build script 😇

**Comment by cmoog** [comment]
Ah, I see. Makes sense.

Thanks for the detailed response and this great solution!
