### ISSUE TITLE
error: ... does not provide attribute 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'

### ISSUE THREAD

**Issue by alexanderkjeldaas** [nix-community/naersk#275]
Running:

```bash
$ nix shell github:jacg/naersk-test-drive/nightly -c naersk-test-drive
error: flake 'github:jacg/naersk-test-drive/nightly' does not provide attribute 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
$ nix shell github:jacg/naersk-test-drive/stable-1.50.0 -c naersk-test-drive
error: flake 'github:jacg/naersk-test-drive/stable-1.50.0' does not provide attribute 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
```

It seems like aarch64-darwin is not supported?  If this is so, it would be good to have it documented in the `README`.

Alternatively, if the above commands are not the correct ones to use, maybe add a `shell` command that can be used to run `naersk`.

The commands [are from this post](https://discourse.nixos.org/t/how-to-use-naersk-with-stable-rust-tools/11712) which is the only one I could find that documents a command to use.

**Comment by Patryk27** [comment]
Naersk can be used with aarch64-darwin - it's just the the repository you've linked is a bit old and uses [flake-utils](https://github.com/numtide/flake-utils) from the time where _it_ didn't know that aarch64-darwin existed.

That is, the code in that repository does:
```nix
{
  # ...

  outputs = { self, nixpkgs, utils, naersk, mozillapkgs }:
    utils.lib.eachDefaultSystem (system: let
      # ...
    );
}
```
... where this `utils.lib.eachDefaultSystem` (that comes from `flake-utils`) doesn't return `aarch64-darwin`, because at the time (January 2021, judging from `flake.lock`) it was still a freshly-born platform.

If you clone that repository, run `nix flake update` (which will bring new `flake-utils` & `nixpkgs`) and adjust fetching Rust to just:
```nix
rust = (mozilla.rustChannelOf {
  channel = "1.50.0";
  sha256 = "sha256-PkX/nhR3RAi+c7W6bbphN3QbFcStg49hPEOYfvG51lA=";
}).rust;
```

... everything will work perfectly fine 🙂 

(although the build _does_ take a lot of time, not sure why.)

**Comment by Patryk27** [comment]
(I'm going to close this issue to keep the issue tracker tidy, but if you encounter any problems or have any questions, please don't hesitate to write here.)
